my:
  name: test
  age: 12
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${my.name}

spring:
  profiles:
    active: dev


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://218.108.132.66/test
    username: root
    password: rcaproject

server:
  port: 8082