my:
  name: test
  age: 12
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${my.name}

spring:
  profiles:
    active: dev


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1x1bof1ah4a0i63yo.mysql.rds.aliyuncs.com/bootStudy
    username: master
    password: GXLjK_RC35vNwR5

server:
  port: 8082